version: '3.8'

services:
  backend:
    build: ./server
    container_name: express_backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5001:5001"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
